branches:
  only:
    - gh_pages

addons:
  ssh_known_hosts: $REMOTE_HOST

before_install:
  - openssl aes-256-cbc -K $encrypted_9c98897b0577_key -iv $encrypted_9c98897b0577_iv
    -in deploy_rsa.enc -out ~/.ssh/deploy_rsa -d
  - chmod 600 ~/.ssh/deploy_rsa

after_success:
  - ssh "mutoe@$REMOTE_HOST" -p "$REMOTE_PORT" 'cd /home/mutoe/mutoe.com/blog && git pull'
